django-getpaid/django-plans

plans/taxation/eu.py
As of 1st of January 2017, two VAT rates have changed : Luxembourg (from 15 to 17%) and Romania (from 20% to 19% - Romania changed from 24% to 20% in 2016), Greece from 23% to 24% (changed in 2016)
=> New VAT standard rates 2017

plans/contrib.py, plans/models.py
`django-plans` assumes that `django.contrib.sites` is installed. The documentation at https://django-plans.readthedocs.io/en/latest/integration.html doesn't mention anything about having it in `INSTALLED_APPS`
When the `Site` model can't be imported, the item description will not contain the current site's name.
Since `django.contrib.sites` is only used for populating the item description with the site name, falling back to not have the site name in the description mkaes `django.contrib.sites` an optional requirement.
Alternatively, we could fix the issue just on the documentation side by adding `'django.contrib.sites'` to https://github.com/cypreess/django-plans/blob/master/docs/source/integration.rst
=> Remove dependency on django.contrib.sites

.travis.yml, CHANGELOG, README.rst, demo/example/foo/models.py, demo/example/foo/urls.py, demo/example/foo/views.py, demo/example/urls.py, demo/requirements.txt, plans/admin.py, plans/context_processors.py, plans/models.py, plans/views.py, setup.cfg, setup.py, tox.ini
- Explicitly set `on_delete` to `CASCADE` for all models. [The on_delete argument for ForeignKey and OneToOneField is now required in models and migrations. Consider squashing migrations so that you have fewer of them to update.
](https://docs.djangoproject.com/en/2.0/releases/2.0/#features-removed-in-2-0)
- Updated urlpatterns to use `path` instead of `url`. [Simplified URL routing syntax](https://docs.djangoproject.com/en/2.0/releases/2.0/#simplified-url-routing-syntax)
- Updated `reverse` module path.
- Removed call to `User.is_authenticated`. [Using User.is_authenticated() and User.is_anonymous() as methods rather than properties is no longer supported.
](https://docs.djangoproject.com/en/2.0/releases/2.0/#features-removed-in-2-0)
- Changed Django and Python version in …
=> Migrated to Django 2.0.2

plans/models.py
Add more precise exceptions handling on plans.Plan.get_default_plan
=> get_default_plan handling exceptions

CHANGELOG, plans/listeners.py, plans/tasks.py, plans/tests/tests.py
Go through django.contrib.auth.get_user_model() instead of a direct model import.
=> tasks: support customised user model

CHANGELOG, docs/source/settings.rst, plans/importer.py, plans/validators.py
This enables PLANS_VALIDATORS be dynamically generated through lazy imported dict defined throught string.
=> allow dynamically create PLANS_VALIDATORS

plans/templates/plans/order_detail_table.html
Small fix for #77  - don't show extended from and extended until if the value is not known
=> Small fix to the Order date_extended PR

CHANGELOG, plans/validators.py
According to [Django documentation](https://docs.djangoproject.com/en/2.2/ref/forms/validation/#raising-validationerror) the `ValidationError` messages should by parametrized by separate `params` variable.
This enables possibility to use these variables elsewhere in the code and evaluate them programmatically.
This code should be backwards-compatible with current implementations of overridden `QuotaValidator`s, because if the `get_error_message` was overridden, the returned string doesn't contain parameters and is used in the old state.
=> use parameters to compose error messages

plans/templates/plans/order_list.html, plans/templates/plans/pagination.html
and add CSS classes, that allow easy setting with infinite scroll
BTW if you want to enable infinite scroll, the code is:
```python
jQuery(document).ready(function($) {
var infScroll_invoices = new InfiniteScroll( '.order_list .table tbody', {
path: '.pagination__next',
append: '.order_list .table tbody tr',
hideNav: '.pagination',
});
$('.infinite-container').bind("DOMNodeInserted", function(){
new LazyLoad({
elements_selector: ".lazy"
});
});
});
```
=> increase overridability of order_list.html template

plans/models.py
The `get_query_set()` function was renamed to `get_queryset()` from Django 1.6, but `django-plans` didn't reflect that yet.
=> fix managers (get_query_set was renamed to get_queryset from Django 1.6)

plans/models.py
Changed NullBooleanField() [deprecated since Django 3.1] to BooleanField(null=True). Reference: https://docs.djangoproject.com/en/3.1/ref/models/fields/
=> Updated BooleanField in model.py

plans/tests/tests.py, plans/views.py
Fix BillingInfoRedirectView - after https://github.com/django-getpaid/django-plans/commit/bfcde3c44d89e7062f529ae9333a7c4fc18967db the redirect doesn't work without `?next=` in url.
Add tests to test whole BillingInfoRedirectView.
=> Fix redirect with no next url

plans/models.py, plans/tests/tests.py, plans/views.py
Fix #127
- validate also that country code corresponds with country
=> fix #127 (wrong TAX when VAT ID doesn't have country code)

plans/forms.py, plans/models.py, plans/tests/tests.py, plans/utils.py, plans/views.py
If user enters (changes) his/hers VAT ID after the first recurring payment, the VAT in the next recurring payments should update accordingly.
This MR fixes it and adds test for that.
=> fix calculating recurring VAT - it is recalculated every time (in case Billing info changes)

plans/models.py, plans/tests/tests.py
There was one more problem with validation of Greece VAT IDs. This fixes that and adds tests for that.
=> fix Greece tax validation

.coveragerc, .github/workflows/main.yml, demo/example/settings.py, demo/requirements.txt
The codecov coverage previously did collect data only for the example application, so it didn't show anything relevant...
=> fix collectiong coverage in GitHub tests

plans/utils.py
Determining country from IP address is an optional feature.
geolite2 was being imported directly ignoring the usecase
that it might not be installed.
geolite2 import has been moved to the get_contry_code method
inside try-except block.
Closes https://github.com/django-getpaid/django-plans/issues/157
=> Fixed geolite2 import

CHANGELOG, demo/example/sample_plans/templates/plans/billing_info_create_or_update.html, demo/example/sample_plans/templates/plans/plan_table.html, docs/source/invoicing.rst, plans/templates/plans/billing_info_create_or_update.html, plans/tests/tests.py, plans/urls.py, plans/views.py
The current situation with CreateBillingInfo and UpdateBillingInvo views has several disadvantages:
* It gives user unnecessary 404 or other errors if he lands on wrong variant (for example has left the create page in browser and in different tab already created the Billing info)
* Code duplication (at least between templates)
* Unnecessary code
This unifies the two views into one that works both ways.
This makes the code a bit backwards incompatible, because if somebody did override the `billing_info_create.html` or `billing_info_update.html` templates, he has to transform the code into the new `billing_info_create_or_update.html` template. Same applies to the views itself.
I made transitional redirect view from the `billing_info_create` and `billing_info_update` with deprecation …
=> Unify BillingInfo view to only one CreateOrUpdate view

plans/base/models.py
`values(...).last()` returns a dict, on which `getattr` doesn't work, so `get_initial_number` always returned 1 instead of the highest `Invoice.number`
=> Fix base/models/get_initial_number not fetching the highest number

CHANGELOG, plans/management/commands/autorenew_accounts.py, plans/tasks.py
[autorenew_accounts: add possibility to throttle between renewals](https://github.com/django-getpaid/django-plans/commit/54a61223de84c4f2ad384fd62f17576ce328283b)
=> Throttle autorenew
